premier_league_teams = {
    "Liverpool": ["L40TH", "https://www.liverpoolfc.com/tickets/tickets-availability"],
    "Manchester City": ["M113FF", "https://www.mancity.com/tickets/mens"],
    "Arsenal": ["N51BU", "https://www.arsenal.com/tickets"],
    "Chelsea": ["SW61HS", "https://www.chelseafc.com/en/ticket-information"],
    "Aston Villa": ["B66HE", "https://www.avfc.co.uk/fans/fans-charter/ticketing/"],
    "Brighton": ["BN19BL", "https://tickets.brightonandhovealbion.com/"],
    "Newcastle": ["NE14ST", "https://tickets.manutd.com/"],
    "Fulham": ["SW66HH", "https://www.fulhamfc.com/tickets-and-hospitality"],
    "Tottenham": ["N170AP", "https://www.tottenhamhotspur.com/tickets"],
    "Nottingham Forest": ["NG25FJ", "https://www.eticketing.co.uk/nottinghamforest"],
    "Brentford": ["TW80NT", "https://www.eticketing.co.uk/brentfordfc"],
    "West Ham": ["E202ST", "https://www.eticketing.co.uk/whufc"],
    "Bournemouth": ["BH77AF", "https://www.afcb.co.uk/tickets/"],
    "Manchester United": ["M160RA", "https://www.manutd.com/tickets"],
    "Leicester": [
        "LE27FL",
        "https://www.premierleague.com/www.lcfc.com/season-tickets",
    ],
    "Everton": ["L44EL", "https://www.evertonfc.com/tickets/latest"],
    "Ipswich": ["IP12DA", "https://tickets.itfc.co.uk/"],
    "Crystal Palace": ["SE256PU", "https://www.eticketing.co.uk/cpfc/"],
    "Southampton": [
        "SO145FP",
        "https://www.premierleague.com/southamptonfc.com/match-tickets",
    ],
    "Wolves": ["WV14QR", "https://www.eticketing.co.uk/wolves"],
}
