name: Docker Image CI


on:
  workflow_run:
    workflows: ["Python package"] # Name of the first workflow
    types:
      - completed

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Your Docker Hub username secret
  IMAGE_NAME: football  # Name of your Docker Hub image

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Log into Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}  # Use the username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use the access token from secrets

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
