name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: samdroberts  # Replace with your Docker Hub username
  IMAGE_NAME: football  # Name of your Docker Hub image

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Log into Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # You should store your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # You should store your Docker Hub access token in GitHub Secrets

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$(date +%s)

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$(date +%s)
